### ISSUE TITLE
[Bug] [bluray_info] Json produced by filtered output is incorrect

### ISSUE THREAD

**Issue by zscholl** [beandog/bluray_info#13]
## Thank you!
First off, thank you for these amazing tools! I was using `makemkv` and found it to be entirely confusing and not intuitive from the command line.

I wanted to report a minor issue with json output that only seems to happen if you filter the titles. Here are the details:

### Example
```bash
$ bluray_info -j > all_titles.json
$ jq . all_titles.json
... all valid json ...
```

```bash
$ bluray_info -M 20 -j > long_titles.json
$ jq . long_titles.json
parse error: Expected another array element at line 1504, column 2
```

## Notes
It seems like it's adding an extra `,` at the end of the last `title` entry when it shouldn't.

vim syntax highlighting:
<img width="273" alt="Screenshot 2023-01-05 at 10 12 43 AM" src="https://user-images.githubusercontent.com/8786230/210827519-4a4d9bcf-e37e-4524-8339-a5cc230b4d7d.png">
[](url)
I've attached the two json files I generated using those commands here. They're from disc one of Cowboy Bebop. Github won't let me attach `.json` extensions 🙄 
[all_titles.txt](https://github.com/beandog/bluray_info/files/10353753/all_titles.txt)
[long_titles.txt](https://github.com/beandog/bluray_info/files/10353757/long_titles.txt)

**Comment by beandog** [comment]
Thanks for the report @zscholl! It's fixed in tree, will go out in next release.

**Comment by beandog** [comment]
Ok 1.10 is out, let me know if you have any more problems, thanks!
